# 关键帧
data_path: ./   # 数据存放路径

extend_frame_num: 5 
loop_step: 5 # 防止检测过于频繁，每隔loop_step个关键帧检测一次闭环
detect_area: 10.0 # 检测区域，只有两帧距离小于这个值，才做闭环匹配
diff_num: 100 # 过于小的闭环没有意义，所以只有两帧之间的关键帧个数超出这个值再做检测
fitness_score_limit: 0.2 # 匹配误差小于这个值才认为是有效的