map_path: /home/g/workspace/multisensor_fusion_localization_study/catkin_myspace/src/multisensor_localization/data/map/map.pcd
registration_method: NDT
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30

current_scan_filter: voxel_filter 
local_map_filter: voxel_filter 
global_map_filter: voxel_filter

voxel_filter:
    global_map:
        leaf_size: [0.9, 0.9, 0.9]
    local_map:
        leaf_size: [0.5, 0.5, 0.5]
    current_scan:
        leaf_size: [1.5, 1.5, 1.5]

box_filter_size: [-150.0, 150.0, -150.0, 150.0, -150.0, 150.0]
